### ISSUE TITLE
Should Base.keys(ds) default to varnames(ds)

### ISSUE THREAD

**Issue by lupemba** [JuliaGeo/CommonDataModel.jl#25]
Reading the documentation it looks like that `varnames` should be implemented for each `AbstractDataset` but my experience with [MetopNative.jl](https://gitlab.eumetsat.int/eumetlab/cross-cutting-tools/MetopNative.jl) is that `CommonDataModel.jl` relies more on `Base.keys` e.g. in the `show` method https://github.com/JuliaGeo/CommonDataModel.jl/blob/e63005450f5694581ba16cd39c5d2d669825d90b/src/dataset.jl#L99

An easy fix for this could be to add `varnames` as the fallback method.
```julia
Base.keys(ds::AbstractDataset) = varnames(ds)
```

I might try to make a PR tomorrow.

**Comment by Alexander-Barth** [comment]
Yes, that is a good idea! Thanks!
